server:
  port: 8025

spring:
  application:
    name: mcp-router

# 路由器特定配置
mcp:
  router:
    # 负载均衡策略
    load-balance-strategy: least-loaded
    # 健康检查间隔（毫秒）
    health-check-interval: 30000
    # 服务降级阈值
    degraded-threshold: 0.7

# 日志配置
logging:
  level:
    com.mcp.router: DEBUG

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: ALWAYS 