server:
  port: 8080

spring:
  application:
    name: mcp-client
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key}
      chat:
        options:
          model: gpt-3.5-turbo

# Removed Eureka configuration
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.cloud.client.ip-address}:${server.port}

mcp:
  server:
    url: http://mcp-server-weather
  server-two:
    url: http://mcp-server-book 