server:
  port: 18082

spring:
  application:
    name: mcp-server-two
  datasource:
    url: jdbc:h2:mem:mcpdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

# Health endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Removed Eureka configuration
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mcp.servertwo.model 

logging:
  level:
    root: INFO
    com.mcp.servertwo: DEBUG
    org.mybatis: DEBUG
    org.springframework.jdbc: DEBUG 